blueprint:
  name: Notify on Zone Entrance or Exit (Fixed)
  description: Send a notification to a specific device when a person enters or leaves a specified zone.
  domain: automation
  input:
    person_entity:
      name: Tracked Person
      selector:
        entity:
          filter:
            domain: person
    zone_entity:
      name: Target Zone
      selector:
        entity:
          filter:
            domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          filter:
            integration: mobile_app

mode: restart

triggers:
  - trigger: state
    entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

conditions:
  - condition: template
    value_template: >-
      {% set home_enter = (zone_entity == 'zone.home' and trigger.from_state.state != 'home' and trigger.to_state.state == 'home') %}
      {% set home_leave = (zone_entity == 'zone.home' and trigger.from_state.state == 'home' and trigger.to_state.state != 'home') %}
      {% set other_enter = (zone_entity != 'zone.home' and trigger.from_state.state != zone_state and trigger.to_state.state == zone_state) %}
      {% set other_leave = (zone_entity != 'zone.home' and trigger.from_state.state == zone_state and trigger.to_state.state != zone_state) %}
      {{ home_enter or home_leave or other_enter or other_leave }}

actions:
  - alias: "Notify that a person has moved"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: >-
      {% set current_state = trigger.to_state.state %}
      {% if zone_entity == 'zone.home' %}
        {% if current_state == 'home' %}
          {{ person_name }} has arrived Home
        {% else %}
          {{ person_name }} has left Home
        {% endif %}
      {% else %}
        {% if current_state == zone_state %}
          {{ person_name }} has arrived at {{ zone_state }}
        {% else %}
          {{ person_name }} has left {{ zone_state }}
        {% endif %}
      {% endif %}
